### ISSUE TITLE
Broken Images

### ISSUE THREAD

**Issue by jkga** [wareneutron/covid19-tracker-cli#62]
**Details**
> Some images are not showing in `Readme.md`. Please Refer to the screenshot below

![image](https://user-images.githubusercontent.com/10413754/112002024-728b9580-8b5a-11eb-9304-eec7596ac401.png)

**Comment by jcads** [comment]
Hi, @WarenGonzaga can I pick this up?

**Comment by WarenGonzaga** [comment]
@jcads assigned to you! Good luck!

**Comment by jcads** [comment]
Should the PR be opened to the `dev` branch?

**Comment by WarenGonzaga** [comment]
Closing this! Looking forward to your next contribution @jcads!
