### ISSUE TITLE
Typescript Migration

### ISSUE THREAD

**Issue by WarenGonzaga** [wareneutron/covid19-tracker-cli#64]
Making the project TS friendly and also moving to yarn. Can you work on it? @scinscinscin

**Comment by scinscinscin** [comment]
I am doing a complete rewrite of the API

**Comment by scinscinscin** [comment]
So... here's where I am with the typescript rewrite.
I made my own table-making utility that has support for both ANSI and asciichart.
I didn't change what information the tables showed.

I modified some of the routes and added some features.
Here are all the routes that the API has right now

<details>
<summary>Show rewritten features</summary>

**Global information**
![Global information](https://user-images.githubusercontent.com/65155829/112752670-b07b3480-9006-11eb-9839-9c82634b1fa5.png)

**Per country information**
![Per country information](https://user-images.githubusercontent.com/65155829/112752700-e0c2d300-9006-11eb-9d09-cb0f140f962d.png)

**Global historical chart**
![image](https://user-images.githubusercontent.com/65155829/112752718-f0dab280-9006-11eb-92ed-ca31999c798a.png)

**Per country historical chart**
![Per country historical chart](https://user-images.githubusercontent.com/65155829/112752764-254e6e80-9007-11eb-8017-de94e3227b67.png)

</details>

<details>
<summary>Show new features</summary>

**Append /recovered or /deaths to /history/ or /history/:countryName to show recovered or deaths in the graph**
![new feature](https://user-images.githubusercontent.com/65155829/112752924-fbe21280-9007-11eb-935d-d8c33061d674.png)

**Error handling**
![Error handling](https://user-images.githubusercontent.com/65155829/112752983-554a4180-9008-11eb-9293-351814271f25.png)

</details>

**Comment by WarenGonzaga** [comment]
Good work @scinscinscin!

For the last part ``/history/charts/:country endpoint``

This mean, you don't touch this part? Is this because it is part of GFX right?

**Comment by WarenGonzaga** [comment]
Closing this since it is already on branch v4
